version: "3.1"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysqldata:/var/db/mysql/
    ports:
      - "3306:3306"
volumes:
  mysqldata: